name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: pedrowilliam
  REPO: pedrowilliam/automate-build-release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Semantic versioning
        id: versioning
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-prerelease${increment}"
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.REPO }}:latest,${{ env.REPO }}:${{ steps.versioning.outputs.version }}
          
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.versioning.outputs.version }}
          name: ${{ steps.versioning.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
